<?php

namespace Database\Seeders;

use App\Models\Technique;
use Illuminate\Database\Seeder;

class TechniqueSeeder extends Seeder
{
    public function run(): void
    {
        $techniques = [
            // ================== ANSIEDAD ==================
            [
                'name' => 'Respiración Diafragmática',
                'slug' => 'respiracion-diafragmatica',
                'category' => 'ansiedad',
                'description' => 'Técnica fundamental que estimula el nervio vago y activa el sistema nervioso parasimpático, reduciendo el ritmo cardíaco y la sensación de alarma.',
                'benefits' => "• Reduce de forma inmediata la aceleración cardíaca y la hiperventilación.\n• Favorece una oxigenación celular profunda y eficiente.\n• Disminuye la tensión en pecho y hombros.",
                'instructions' => [
                    'Coloca una mano en tu pecho y la otra sobre tu abdomen.',
                    'Inhala despacio por la nariz durante 4 segundos sintiendo cómo tu abdomen se expande.',
                    'Sostén el aire con calma durante 2 segundos.',
                    'Exhala suavemente por la boca durante 5 segundos, notando cómo desciende el abdomen.',
                    'Repite el ciclo durante 3 a 5 minutos manteniendo un ritmo fluido.',
                ],
                'animation_type' => 'breathing',
                'duration_minutes' => 4,
                'order' => 1,
                'active' => true,
            ],
            [
                'name' => 'Respiración 4-7-8',
                'slug' => 'respiracion-4-7-8',
                'category' => 'ansiedad',
                'description' => 'Patrón respiratorio para inducir calma profunda, desacelerar pensamientos acelerados y preparar el cuerpo para el descanso.',
                'benefits' => "• Actúa como tranquilizante natural para el sistema nervioso.\n• Ayuda a frenar episodios de rumiación mental y angustia.\n• Mejora la conciliación del sueño.",
                'instructions' => [
                    'Adopta una postura cómoda con la espalda recta y suelta los hombros.',
                    'Inhala silenciosamente por la nariz contando hasta 4.',
                    'Mantén la respiración de forma relajada durante 7 segundos.',
                    'Exhala por la boca emitiendo un suave suspiro durante 8 segundos.',
                    'Completa 4 ciclos consecutivos prestando atención a la sensación de liberación.',
                ],
                'animation_type' => 'breathing',
                'duration_minutes' => 4,
                'order' => 2,
                'active' => true,
            ],
            [
                'name' => 'Respiración en Caja (Box Breathing)',
                'slug' => 'respiracion-en-caja',
                'category' => 'ansiedad',
                'description' => 'Técnica de autorregulación utilizada por fuerzas especiales y atletas de élite para restablecer la claridad mental ante presión extrema.',
                'benefits' => "• Equilibra la concentración y neutraliza la respuesta de lucha o huida.\n• Estabiliza la variabilidad de la frecuencia cardíaca.\n• Ideal antes de presentaciones, exámenes o reuniones.",
                'instructions' => [
                    'Inhala por la nariz contando: 1, 2, 3, 4.',
                    'Retén el aire con los pulmones llenos contando: 1, 2, 3, 4.',
                    'Exhala completamente el aire por la boca contando: 1, 2, 3, 4.',
                    'Permanece con los pulmones vacíos en calma contando: 1, 2, 3, 4.',
                    'Continúa la secuencia visualizando los cuatro lados de un cuadrado.',
                ],
                'animation_type' => 'breathing',
                'duration_minutes' => 5,
                'order' => 3,
                'active' => true,
            ],
            [
                'name' => 'Grounding 5-4-3-2-1 (Anclaje Sensorial)',
                'slug' => 'grounding-5-4-3-2-1',
                'category' => 'ansiedad',
                'description' => 'Ejercicio de anclaje cognitivo-sensorial que reconecta la atención con el momento presente y desactiva la rumiación ansiosa en minutos.',
                'benefits' => "• Interrumpe espirales de preocupación y pánico inmediato.\n• Redirige el foco desde la mente hacia el entorno físico seguro.\n• Brinda sensación de control y presencia.",
                'instructions' => [
                    '👁️ Observa y nombra 5 COSAS QUE PUEDAS VER a tu alrededor.',
                    '✋ Toca y siente 4 COSAS QUE PUEDAS TOCAR (tu ropa, la mesa, tus manos).',
                    '👂 Detecta 3 SONIDOS QUE PUEDAS ESCUCHAR en este momento.',
                    '👃 Identifica 2 AROMAS U OLORES que puedas percibir.',
                    '👅 Reconoce 1 SABOR EN TU BOCA (o toma un sorbo consciente de agua).',
                    'Respira profundo y siente tus pies firmes apoyados en el suelo.',
                ],
                'animation_type' => 'grounding',
                'duration_minutes' => 5,
                'order' => 4,
                'active' => true,
            ],
            [
                'name' => 'Visualización de un Lugar Seguro',
                'slug' => 'visualizacion-lugar-seguro',
                'category' => 'ansiedad',
                'description' => 'Ejercicio de imaginería guiada que usa el poder de la mente para generar una respuesta neurobiológica de paz y serenidad.',
                'benefits' => "• Genera sensaciones de bienestar y alivio somático.\n• Reduce los niveles de cortisol mediante evocación sensorial positiva.\n• Fortalece la sensación interna de seguridad.",
                'instructions' => [
                    'Cierra los ojos y respira suavemente por unos instantes.',
                    'Imagina un lugar donde te sientas en absoluta calma y comodidad.',
                    'Observa los colores, la luz cálida y los detalles visuales de este entorno.',
                    'Escucha los sonidos agradables que habitan en este espacio.',
                    'Siente la temperatura reconfortante sobre tu piel y la seguridad en tu pecho.',
                    'Permanece allí reconociendo que este espacio siempre vive dentro de ti.',
                ],
                'animation_type' => 'visualization',
                'duration_minutes' => 6,
                'order' => 5,
                'active' => true,
            ],
            [
                'name' => 'Técnica de Defusión Cognitiva',
                'slug' => 'defusion-cognitiva',
                'category' => 'ansiedad',
                'description' => 'Técnica de la Terapia de Aceptación y Compromiso (ACT) para crear distancia psicológica de los pensamientos ansiosos, observándolos sin identificarse con ellos.',
                'benefits' => "• Reduce la fusión mental con pensamientos catastróficos.\n• Permite elegir respuestas en lugar de reaccionar automáticamente.\n• Disminuye la angustia ante pensamientos intrusivos.",
                'instructions' => [
                    'Identifica el pensamiento ansioso que más te perturbada en este momento. Por ejemplo: "Voy a fracasar".',
                    'Ahora anteponle la frase: "Estoy teniendo el pensamiento de que... voy a fracasar".',
                    'Luego añade: "Noto que estoy teniendo el pensamiento de que voy a fracasar".',
                    'Imagina ese pensamiento como una nube que pasa por el cielo o una hoja flotando en un río.',
                    'Observa el pensamiento desde la orilla, sin subirte a él. Solo obsérvalo pasar.',
                    'Respira y regresa a lo que sea que necesitas hacer ahora.',
                ],
                'animation_type' => 'visualization',
                'duration_minutes' => 5,
                'order' => 6,
                'active' => true,
            ],
            [
                'name' => 'Relajación por Inducción Autógena',
                'slug' => 'relajacion-autogena',
                'category' => 'ansiedad',
                'description' => 'Método clásico del Dr. Johannes Schultz que usa auto-sugestiones de calor y pesadez para inducir un estado de relajación profunda desde dentro.',
                'benefits' => "• Activa la respuesta de relajación del sistema nervioso autónomo.\n• Reduce la presión arterial y la frecuencia cardíaca.\n• Útil ante ataques de pánico y tensión generalizada.",
                'instructions' => [
                    'Siéntate o recuéstate en una posición cómoda y cierra los ojos.',
                    'Repite internamente: "Mi brazo derecho está pesado, muy pesado..." (3 veces).',
                    'Continúa: "Mi brazo derecho está cálido, muy cálido..." (3 veces).',
                    'Extiende la sugestión a ambos brazos, piernas y todo el cuerpo.',
                    'Finaliza con: "Mi corazón late de forma calmada y regular. Estoy en paz."',
                    'Permanece en este estado 2-3 minutos y luego abre los ojos lentamente.',
                ],
                'animation_type' => 'visualization',
                'duration_minutes' => 8,
                'order' => 7,
                'active' => true,
            ],

            // ================== ESTRÉS ==================
            [
                'name' => 'Relajación Muscular Progresiva (Jacobson)',
                'slug' => 'relajacion-muscular-progresiva',
                'category' => 'estres',
                'description' => 'Método fisiológico basado en la contracción y distensión voluntaria de diferentes grupos musculares para liberar el estrés somatizado.',
                'benefits' => "• Enseña a detectar y disipar la rigidez muscular involuntaria.\n• Reduce contracturas en cuello, espalda y hombros.\n• Disminuye la sobreexcitación del sistema nervioso central.",
                'instructions' => [
                    'Pies y piernas: Tensa los músculos durante 5 segundos. Luego suelta de golpe por 10 segundos.',
                    'Abdomen y glúteos: Aprieta fuertemente 5 segundos. Libera y respira con soltura.',
                    'Brazos y manos: Cierra los puños 5 segundos. Abre las manos y siente el calor de la distensión.',
                    'Hombros y cuello: Eleva los hombros hacia las orejas 5 segundos. Déjalos caer con un suspiro.',
                    'Rostro: Arruga la frente, aprieta los ojos y la mandíbula 5 segundos. Relaja por completo.',
                    'Disfruta la sensación de liviandad en todo el cuerpo.',
                ],
                'animation_type' => 'muscle_relaxation',
                'duration_minutes' => 8,
                'order' => 8,
                'active' => true,
            ],
            [
                'name' => 'Escaneo Corporal (Body Scan)',
                'slug' => 'escaneo-corporal',
                'category' => 'estres',
                'description' => 'Práctica de atención plena que recorre secuencialmente cada zona del cuerpo para reconocer tensiones sin juzgarlas y propiciar su disolución.',
                'benefits' => "• Aumenta la conciencia corporal y la conexión mente-cuerpo.\n• Desactiva la sobrecarga cognitiva del trabajo y estudio.\n• Facilita la relajación profunda antes de dormir.",
                'instructions' => [
                    'Acomódate en una silla o recuéstate cómodamente y cierra los ojos.',
                    'Dirige tu atención hacia la planta de tus pies, notando calor, cosquilleo o apoyo.',
                    'Sube con suavidad por pantorrillas, rodillas y muslos, liberando cualquier peso.',
                    'Observa tu espalda y el vaivén de tu abdomen con cada respiración.',
                    'Lleva la atención a tu pecho, cuello, mandíbula y frente, invitando a cada músculo a aflojarse.',
                    'Siente la totalidad de tu cuerpo descansando en este momento presente.',
                ],
                'animation_type' => 'visualization',
                'duration_minutes' => 7,
                'order' => 9,
                'active' => true,
            ],
            [
                'name' => 'Mindfulness Breve (Anclaje en la Respiración)',
                'slug' => 'mindfulness-breve',
                'category' => 'estres',
                'description' => 'Entrenamiento atencional para salir del piloto automático, observar los pensamientos sin identificarse con ellos y recuperar la calma mental.',
                'benefits' => "• Fomenta la claridad mental y el enfoque.\n• Reduce la reactividad emocional ante los estresores.\n• Permite tomar decisiones más conscientes y pausadas.",
                'instructions' => [
                    'Siéntate con la espalda erguida pero relajada, apoyando las manos sobre el regazo.',
                    'Elige un punto de anclaje: el roce del aire en la nariz o el movimiento de tu pecho.',
                    'Observa cada respiración tal y como surge, sin intentar cambiarla.',
                    'Cuando notes que tu mente se distrae, reconócelo amablemente y regresa al anclaje.',
                    'Concluye agradeciéndote este espacio de pausa y claridad.',
                ],
                'animation_type' => 'breathing',
                'duration_minutes' => 5,
                'order' => 10,
                'active' => true,
            ],
            [
                'name' => 'Técnica STOP',
                'slug' => 'tecnica-stop',
                'category' => 'estres',
                'description' => 'Micro-intervención rápida de cuatro pasos para aplicar cuando sientes que el estrés empieza a sobrepasarte en jornadas demandantes.',
                'benefits' => "• Previene reacciones impulsivas o desgastantes.\n• Restablece la perspectiva en menos de 2 minutos.\n• Fácil de aplicar en cualquier entorno laboral o escolar.",
                'instructions' => [
                    'S — Stop / Para: Detén lo que estás haciendo por un instante.',
                    'T — Toma aire: Realiza una o dos respiraciones profundas y conscientes.',
                    'O — Observa: ¿Qué estoy pensando? ¿Qué emoción siento? ¿Qué tensión física experimento?',
                    'P — Procede: Continúa desde una postura más centrada, eligiendo lo más prioritario.',
                ],
                'animation_type' => 'grounding',
                'duration_minutes' => 3,
                'order' => 11,
                'active' => true,
            ],
            [
                'name' => 'Escritura Expresiva (Journaling Terapéutico)',
                'slug' => 'escritura-expresiva',
                'category' => 'estres',
                'description' => 'Técnica basada en las investigaciones de James Pennebaker: escribir libremente sobre emociones y pensamientos difíciles para reducir la carga mental del estrés.',
                'benefits' => "• Procesa y ordena emociones caóticas acumuladas.\n• Reduce rumiación mental y preocupación nocturna.\n• Fortalece la resiliencia emocional con la práctica.",
                'instructions' => [
                    'Busca un espacio privado y un cuaderno o hoja en blanco.',
                    'Escribe sin censura sobre lo que más te está generando estrés. No importa la ortografía ni la lógica.',
                    'Describe qué sientes en el cuerpo cuando piensas en ello: ¿presión en el pecho, nudo en la garganta?',
                    'Escribe al menos 15-20 minutos sin levantar la mano del papel.',
                    'Al finalizar, escribe UNA COSA pequeña que sí esté en tu control hacer hoy.',
                    'Guarda o descarta lo escrito: lo valioso ya ocurrió al sacarlo.',
                ],
                'animation_type' => 'grounding',
                'duration_minutes' => 20,
                'order' => 12,
                'active' => true,
            ],
            [
                'name' => 'Meditación de Compasión (Loving-Kindness)',
                'slug' => 'meditacion-compasion',
                'category' => 'estres',
                'description' => 'Práctica budista adaptada clínicamente que cultiva sentimientos de amor incondicional y bondad hacia uno mismo y los demás para reducir el autocrítica y el estrés social.',
                'benefits' => "• Reduce la autocrítica y el perfeccionismo exigente.\n• Aumenta emociones positivas como gratitud y conexión.\n• Mejora las relaciones interpersonales y la empatía.",
                'instructions' => [
                    'Cierra los ojos y respira suavemente. Lleva la atención a tu corazón.',
                    'Repite internamente estas frases hacia ti mismo(a): "Que yo esté bien. Que yo sea feliz. Que yo esté en paz."',
                    'Visualiza a alguien que amas y dirígele las mismas frases: "Que tú estés bien. Que tú seas feliz. Que tú estés en paz."',
                    'Extiende estos deseos a personas conocidas, luego a desconocidos y finalmente a todos los seres.',
                    'Regresa a ti: recibe todo ese amor y bienestar como si fuera una luz cálida que te envuelve.',
                    'Abre los ojos lentamente con gratitud.',
                ],
                'animation_type' => 'visualization',
                'duration_minutes' => 10,
                'order' => 13,
                'active' => true,
            ],
            [
                'name' => 'Técnica de Resolución de Problemas (PST)',
                'slug' => 'resolucion-de-problemas',
                'category' => 'estres',
                'description' => 'Método cognitivo estructurado derivado de la Terapia de Resolución de Problemas (D\'Zurilla & Goldfried) para transformar estresores identificables en acciones concretas.',
                'benefits' => "• Convierte la preocupación vaga en planes de acción claros.\n• Reduce la sensación de impotencia ante situaciones difíciles.\n• Desarrolla la capacidad de afrontamiento activo.",
                'instructions' => [
                    '1. DEFINE el problema: Escribe en una frase concreta cuál es el problema específico.',
                    '2. GENERA soluciones: Lista al menos 5 posibles soluciones sin juzgarlas (lluvia de ideas libre).',
                    '3. EVALÚA cada solución: ¿Es realista? ¿Cuáles son sus consecuencias positivas y negativas?',
                    '4. ELIGE la mejor opción o combinación de opciones.',
                    '5. ACTÚA: Define los primeros 3 pasos concretos que puedes tomar hoy.',
                    '6. EVALÚA los resultados y ajusta si es necesario. El intento ya es un éxito.',
                ],
                'animation_type' => 'grounding',
                'duration_minutes' => 15,
                'order' => 14,
                'active' => true,
            ],

            // ================== NUEVAS (2026) ==================
            [
                'name' => 'Reestructuración Cognitiva ABC (Ellis)',
                'slug' => 'reestructuracion-cognitiva-abc',
                'category' => 'ansiedad',
                'description' => 'Técnica de la Terapia Racional Emotiva Conductual (Albert Ellis) para identificar el pensamiento automático detrás de una emoción incómoda y cuestionarlo con evidencia, en vez de solo observarlo.',
                'benefits' => "• Ayuda a distinguir el hecho (A) de la interpretación (B) que realmente genera la emoción (C).\n• Reduce pensamientos catastróficos e ideas irracionales del tipo \"debo ser perfecto\" o \"no puedo fallar\".\n• Desarrolla el hábito de cuestionar pensamientos antes de creerlos automáticamente.",
                'instructions' => [
                    'A - Antecedente: Escribe brevemente la situación concreta que disparó la emoción incómoda.',
                    'C - Consecuencia: Nombra la emoción que sentiste y qué tan intensa fue (0 a 10).',
                    'B - Creencia: Escribe el pensamiento exacto que pasó por tu mente justo antes de sentir esa emoción.',
                    'Pregúntate: ¿Qué evidencia real tengo de que ese pensamiento es cierto? ¿Qué evidencia tengo en contra?',
                    'Pregúntate: ¿Le diría esto mismo a un amigo en mi misma situación?',
                    'Escribe un pensamiento alternativo más realista y equilibrado para reemplazar al original.',
                ],
                'animation_type' => 'grounding',
                'duration_minutes' => 9,
                'order' => 15,
                'active' => true,
            ],
            [
                'name' => 'Activación Conductual Breve',
                'slug' => 'activacion-conductual-breve',
                'category' => 'estres',
                'description' => 'Técnica derivada de la activación conductual en TCC para romper el ciclo de evitación y bajo ánimo, planificando una actividad pequeña y concreta en vez de esperar a "tener ganas".',
                'benefits' => "• Interrumpe el círculo vicioso de evitación → más bajo ánimo → más evitación.\n• Genera una sensación de logro y control incluso en días difíciles.\n• No depende de la motivación: la acción antecede al ánimo, no al revés.",
                'instructions' => [
                    'Reconoce si llevas un tiempo evitando actividades que antes hacías con normalidad.',
                    'Elige UNA actividad pequeña y concreta que puedas hacer hoy (no una lista larga).',
                    'Que sea de alguno de estos dos tipos: una actividad AGRADABLE (algo que disfrutas) o una de DOMINIO (algo que necesitas resolver y te dará satisfacción al terminarla).',
                    'Define exactamente cuándo la harás hoy y cuánto tiempo le dedicarás (empieza con 10-15 minutos si tienes poca energía).',
                    'Realízala sin esperar sentir ganas primero. La motivación suele aparecer después de empezar, no antes.',
                    'Al terminar, reconoce el logro por pequeño que parezca: lo hiciste incluso sin ganas.',
                ],
                'animation_type' => 'grounding',
                'duration_minutes' => 15,
                'order' => 16,
                'active' => true,
            ],
            [
                'name' => 'Exposición Gradual Cotidiana',
                'slug' => 'exposicion-gradual-cotidiana',
                'category' => 'ansiedad',
                'description' => 'Versión leve y no clínica de la desensibilización sistemática: enfrentar de forma progresiva una situación cotidiana que evitas por ansiedad, empezando por el paso menos amenazante. No sustituye tratamiento profesional para fobias o ansiedad severa.',
                'benefits' => "• Reduce la evitación, que a corto plazo alivia pero a largo plazo mantiene la ansiedad.\n• Permite comprobar en la práctica que la situación temida es más manejable de lo anticipado.\n• Construye confianza progresiva en vez de exigir un salto brusco.",
                'instructions' => [
                    'Identifica una situación cotidiana leve que evitas por ansiedad (ej. una llamada pendiente, participar en clase, iniciar una conversación).',
                    'Divide esa situación en 4 o 5 pasos, del menos al más incómodo (ej. escribir el guion, practicarlo en voz alta, decirlo frente al espejo, decirlo a alguien de confianza, hacerlo en la situación real).',
                    'Antes de empezar el paso más fácil, aplica una respiración breve (Respiración en Caja o Diafragmática) para bajar la activación inicial.',
                    'Realiza solo el primer paso de la lista. No pases al siguiente hasta sentir que ese nivel de ansiedad es manejable.',
                    'Registra del 0 al 10 tu ansiedad antes y después de cada paso: notarás que suele bajar con la repetición.',
                    'Avanza al siguiente paso solo cuando te sientas listo(a), a tu propio ritmo. Si el riesgo percibido es alto, consulta la sección de Rutas de Ayuda.',
                ],
                'animation_type' => 'grounding',
                'duration_minutes' => 10,
                'order' => 17,
                'active' => true,
            ],
        ];

        foreach ($techniques as $tech) {
            Technique::updateOrCreate(
                ['slug' => $tech['slug']],
                $tech
            );
        }
    }
}-