<?php

/**
 * Sesiones de relajación guiada por voz.
 * Para usar un audio grabado, coloca el archivo en public/audio/relajacion/{slug}.mp3
 * (o .wav / .ogg). Si no hay archivo, el reproductor usa voz del navegador (Web Speech API).
 */
return [
    'audio_path' => 'audio/relajacion',

    'sessions' => [
        [
            'slug' => 'calma-y-tranquilidad',
            'name' => 'Calma y tranquilidad',
            'description' => 'Una pausa breve para suavizar el ritmo interno y volver a un estado más sereno.',
            'duration_seconds' => 300,
            'accent' => '#7D9B76',
            'cues' => [
                ['at' => 0, 'text' => 'Encuentra una posición cómoda. No hay nada que debas resolver en este momento.'],
                ['at' => 25, 'text' => 'Si quieres, cierra los ojos o deja la mirada suave, un poco más abajo.'],
                ['at' => 50, 'text' => 'Permite que tus hombros se relajen. Nota el peso de tu cuerpo sostenido por el asiento o el suelo.'],
                ['at' => 85, 'text' => 'Inhala con calma por la nariz... y exhala un poco más lento, como si el aire se fuera por sí solo.'],
                ['at' => 120, 'text' => 'Observa las sensaciones de tu cuerpo. No tienes que cambiarlas. Solo acompañarlas.'],
                ['at' => 155, 'text' => 'Si aparecen pensamientos, déjalos pasar como nubes. Puedes volver, con suavidad, a la respiración.'],
                ['at' => 195, 'text' => 'Permítete permanecer aquí unos instantes. Un espacio pequeño, suficiente, para ti.'],
                ['at' => 235, 'text' => 'Nota cómo el pecho sube y baja. Un ritmo simple. Un ritmo que ya sabes hacer.'],
                ['at' => 270, 'text' => 'Cuando quieras, puedes ir abriendo los ojos. Lleva contigo un poco de esta calma.'],
            ],
        ],
        [
            'slug' => 'reducir-ansiedad',
            'name' => 'Reducir ansiedad',
            'description' => 'Acompañamiento pausado para cuando el cuerpo está alerta y la mente se adelanta.',
            'duration_seconds' => 360,
            'accent' => '#8FAF88',
            'cues' => [
                ['at' => 0, 'text' => 'Está bien que estés aquí. No necesitas calmarte de inmediato. Solo darte un lugar seguro por unos minutos.'],
                ['at' => 30, 'text' => 'Encuentra una posición cómoda. Siente los pies en el suelo, o el cuerpo apoyado.'],
                ['at' => 60, 'text' => 'Nombra, en silencio, cinco cosas que puedes ver. Luego cuatro que puedes tocar.'],
                ['at' => 100, 'text' => 'Tres sonidos. Dos aromas, si los hay. Un sabor, aunque sea el de tu propia boca.'],
                ['at' => 140, 'text' => 'Esto ayuda a volver al presente. No es una orden. Es una invitación.'],
                ['at' => 175, 'text' => 'Inhala contando hasta cuatro... sostén un instante... y suelta el aire contando hasta seis.'],
                ['at' => 220, 'text' => 'Si la mente corre, no la riñas. Acompáñala de regreso, como a alguien que se adelantó un poco.'],
                ['at' => 260, 'text' => 'Permite que la mandíbula se suelte. Que las manos descansen abiertas.'],
                ['at' => 300, 'text' => 'Observa si hay un poco más de espacio entre un pensamiento y el siguiente.'],
                ['at' => 330, 'text' => 'Cuando quieras, vuelve con suavidad. Puedes quedarte un segundo más antes de continuar el día.'],
            ],
        ],
        [
            'slug' => 'liberar-estres',
            'name' => 'Liberar estrés',
            'description' => 'Una sesión para soltar tensiones acumuladas sin exigirte que todo desaparezca.',
            'duration_seconds' => 420,
            'accent' => '#C4856A',
            'cues' => [
                ['at' => 0, 'text' => 'Has llegado. Puedes dejar, por un rato, la lista de pendientes a un lado.'],
                ['at' => 30, 'text' => 'Encuentra una posición cómoda. Permite que tus hombros bajen un milímetro más.'],
                ['at' => 70, 'text' => 'Inhala llenando el abdomen... y al exhalar, imagina que parte de la carga se va con el aire.'],
                ['at' => 110, 'text' => 'No tienes que vaciarte por completo. Solo soltar un poco.'],
                ['at' => 150, 'text' => 'Recorre tu frente, tus ojos, tu boca. ¿Hay algún gesto de esfuerzo que puedas suavizar?'],
                ['at' => 195, 'text' => 'Lleva la atención a las manos. Ábrelas. Cierra suavemente. Ábrelas otra vez.'],
                ['at' => 240, 'text' => 'El estrés a veces se queda en el cuello y la espalda. No lo empujes. Solo obsérvalo con amabilidad.'],
                ['at' => 290, 'text' => 'Respira. Un ciclo más lento que el anterior, si te es posible.'],
                ['at' => 340, 'text' => 'Permítete permanecer aquí unos instantes, sin producir nada.'],
                ['at' => 385, 'text' => 'Cuando quieras, abre los ojos. Lleva un ritmo un poco más humano a lo que sigue.'],
            ],
        ],
        [
            'slug' => 'relajacion-corporal',
            'name' => 'Relajación corporal',
            'description' => 'Un recorrido suave por el cuerpo, inspirado en la relajación muscular progresiva.',
            'duration_seconds' => 480,
            'accent' => '#4A6A55',
            'cues' => [
                ['at' => 0, 'text' => 'Acómodate. Puedes estar sentada o recostada. El cuerpo ya sabe descansar.'],
                ['at' => 30, 'text' => 'Empieza por los pies. Nota el contacto. No hace falta tensarlos. Solo reconocerlos.'],
                ['at' => 75, 'text' => 'Sube a las pantorrillas y rodillas. Observa las sensaciones de tu cuerpo, sin corregirlas.'],
                ['at' => 120, 'text' => 'Abdomen y pecho. La respiración entra y sale. Tú no tienes que dirigirla del todo.'],
                ['at' => 170, 'text' => 'Manos, brazos, hombros. Permite que se entreguen un poco más al apoyo.'],
                ['at' => 220, 'text' => 'Cuello y mandíbula. Si hay tensión, no la pelees. Dale permiso de existir... y de aflojarse si quiere.'],
                ['at' => 275, 'text' => 'Rostro. Frente. Párpados. Un descanso pequeño, suficiente.'],
                ['at' => 330, 'text' => 'Ahora el cuerpo completo, como una sola pieza sostenida.'],
                ['at' => 385, 'text' => 'Quédate unos ciclos de respiración en esta sensación de unidad.'],
                ['at' => 440, 'text' => 'Cuando quieras, mueve con suavidad dedos y pies, y vuelve al espacio donde estás.'],
            ],
        ],
        [
            'slug' => 'prepararse-para-dormir',
            'name' => 'Prepararse para dormir',
            'description' => 'Una transición lenta hacia el descanso. No obliga al sueño: solo lo invita.',
            'duration_seconds' => 600,
            'accent' => '#2C3E35',
            'cues' => [
                ['at' => 0, 'text' => 'Esta sesión es una invitación a bajar el volumen del día. No hay meta. Solo acompañarte.'],
                ['at' => 40, 'text' => 'Acomoda almohada, sábanas, temperatura. Pequeños gestos de cuidado.'],
                ['at' => 85, 'text' => 'Apaga, si puedes, lo que no necesitas. La luz. Las notificaciones. La urgencia.'],
                ['at' => 130, 'text' => 'Inhala por la nariz... exhala por la boca, como un suspiro silencioso.'],
                ['at' => 180, 'text' => 'Si la mente revisa el día, agradece que quiera protegerte. Y dile que puede descansar también.'],
                ['at' => 240, 'text' => 'Permite que tus hombros se relajen. Que el peso se hunda un poco más en la cama.'],
                ['at' => 300, 'text' => 'Cuenta, si quieres, respiraciones lentas. Si te pierdes, empieza de nuevo sin reproche.'],
                ['at' => 370, 'text' => 'No necesitas resolver nada en este momento. El mañana puede esperar.'],
                ['at' => 440, 'text' => 'Observa las sensaciones de tu cuerpo. Calor. Contacto. Oscuridad suave.'],
                ['at' => 510, 'text' => 'Permítete permanecer aquí. Si el sueño llega, déjalo llegar. Si no, igual estás descansando.'],
                ['at' => 560, 'text' => 'Silencio. Estoy cerca, sin pedirte nada. Puedes quedarte en esta calma.'],
            ],
        ],
        [
            'slug' => 'liberar-pensamientos',
            'name' => 'Liberar pensamientos',
            'description' => 'Para cuando la mente se enreda. Un espacio para observar sin pelear con lo que aparece.',
            'duration_seconds' => 420,
            'accent' => '#6B7B6E',
            'cues' => [
                ['at' => 0, 'text' => 'Los pensamientos no son órdenes. Pueden pasar. Tú puedes quedarte.'],
                ['at' => 35, 'text' => 'Encuentra una posición cómoda. Un ancla simple: los pies, o el aire en la nariz.'],
                ['at' => 80, 'text' => 'Cuando aparezca un pensamiento, nómbralo con suavidad: planear, recordar, preocupar... y suéltalo.'],
                ['at' => 130, 'text' => 'No necesitas vaciar la mente. Solo dejar de empujar cada idea.'],
                ['at' => 180, 'text' => 'Vuelve a la respiración como quien vuelve a casa, sin prisa.'],
                ['at' => 230, 'text' => 'Si hay una frase repetida, imagínala escrita en agua. Se deshace un poco.'],
                ['at' => 280, 'text' => 'Observa el espacio entre un pensamiento y el siguiente. Aunque dure un segundo.'],
                ['at' => 330, 'text' => 'Permítete permanecer aquí unos instantes, sin resolver el rompecabezas ahora.'],
                ['at' => 380, 'text' => 'Cuando quieras, abre los ojos. Puedes llevarte la opción de no creer todo lo que la mente dice.'],
            ],
        ],
    ],
];
